# Generated by Django 3.2.7 on 2021-09-06 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenantuser',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
