# Generated by Django 3.2.7 on 2021-09-29 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_tenantuser_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tenantuser',
            options={'ordering': ['name']},
        ),
    ]
