# Generated by Django 5.0.1 on 2024-01-28 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_tenantuser_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantuser",
            name="is_known",
            field=models.BooleanField(default=False),
        ),
    ]
