[tool.poetry]
name = "rpgnotes"
version = "0.1.0"
description = ""
authors = ["Lukas Winkler <git@lw1.at>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = {extras = ["argon2"], version = "^3.2.6"}
psycopg2 = "^2.9.1"
django-simple-history = "^3.0.0"
django-bootstrap5 = "^2.1.2"
Markdown = "^3.3.4"
bleach = "^4.0.0"
bleach-allowlist = "^1.0.3"
Pillow = "^8.3.1"
sorl-thumbnail = "^12.7.0"
libsass = "^0.21.0"
django-debug-toolbar = "^3.2.2"
django-tenants = "^3.3.2"
django-tenant-users = {git = "https://github.com/Corvia/django-tenant-users.git"}
django-axes = "^5.23.0"
django-registration = "^3.2"
django-csp = "^3.7"
django-redis = "^5.0.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
