[tool.poetry]
name = "rpgnotes"
version = "0.1.0"
description = ""
authors = ["Lukas Winkler <git@lw1.at>"]

[tool.poetry.dependencies]
python = "^3.9"
Django = {extras = ["argon2"], version = "^4.2.0"}
psycopg2 = "^2.9.1"
django-simple-history = "^3.0.0"
django-bootstrap5 = "^23.1"
Markdown = "^3.3.4"
bleach = "^6.0.0"
bleach-allowlist = "^1.0.3"
Pillow = "^9.0.1"
sorl-thumbnail = "^12.7.0"
libsass = "^0.22.0"
django-debug-toolbar = "^4.0.0"
django-tenants = "^3.3.2"
django-tenant-users = {git = "https://github.com/Corvia/django-tenant-users.git"}
django-axes = "^5.23.0"
django-registration = "^3.2"
django-csp = "^3.7"
django-redis = "^5.0.0"
gunicorn = "^20.1.0"
setproctitle = "^1.2.2"
django-extensions = "^3.1.3"
sentry-sdk = "^1.3.1"
django-tree-queries = "^0.14.0"
django-jinja = "^2.9.1"
bpython = "^0.24"

[tool.poetry.dev-dependencies]
Werkzeug = "^2.0.1"
watchdog = "^3.0.0"
bpython = "^0.24.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
