# Generated by Django 3.2.6 on 2021-08-29 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('characters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Loot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_md', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True, editable=False)),
                ('name', models.CharField(max_length=1000)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('value_gold', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Value (Gold)')),
                ('magic_item', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.character')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalLoot',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description_md', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True, editable=False)),
                ('name', models.CharField(max_length=1000)),
                ('quantity', models.PositiveSmallIntegerField()),
                ('value_gold', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Value (Gold)')),
                ('magic_item', models.BooleanField(default=False)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='characters.character')),
            ],
            options={
                'verbose_name': 'historical loot',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
