# Generated by Django 3.2.7 on 2021-09-15 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0006_auto_20210914_1915'),
        ('loot', '0002_auto_20210906_2011'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloot',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='characters.character', verbose_name='Claimant'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='characters.character', verbose_name='Claimant'),
        ),
    ]
