# Generated by Django 3.2.7 on 2021-09-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0004_auto_20210923_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloot',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight (lb)'),
        ),
        migrations.AddField(
            model_name='loot',
            name='weight',
            field=models.FloatField(blank=True, null=True, verbose_name='Weight (lb)'),
        ),
    ]
