# Generated by Django 3.2.7 on 2021-09-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0005_auto_20210925_1930'),
        ('loot', '0005_auto_20210925_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloot',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='historicalloot',
            name='magic_item',
            field=models.BooleanField(default=False, verbose_name='Magic Item'),
        ),
        migrations.AlterField(
            model_name='historicalloot',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalloot',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='magic_item',
            field=models.BooleanField(default=False, verbose_name='Magic Item'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='quantity',
            field=models.PositiveSmallIntegerField(verbose_name='Quantity'),
        ),
    ]
