# Generated by Django 3.2.7 on 2021-09-25 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0006_auto_20210925_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalloot',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Loot'},
        ),
        migrations.AlterModelOptions(
            name='loot',
            options={'ordering': ['name'], 'verbose_name': 'Loot', 'verbose_name_plural': 'Loot'},
        ),
    ]
