# Generated by Django 3.2.7 on 2021-10-07 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0007_auto_20211007_2254'),
        ('characters', '0012_alter_character_faction'),
        ('loot', '0007_auto_20210925_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loot',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loot', to='locations.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='loot', to='characters.character', verbose_name='Claimant'),
        ),
    ]
