# Generated by Django 3.2.8 on 2021-10-17 16:50

from django.db import migrations, models
import sorl.thumbnail.fields
import utils.random_filename


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0008_auto_20211007_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalloot',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='loot',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=utils.random_filename.get_file_path, verbose_name='Image'),
        ),
    ]
