# Generated by Django 4.0.3 on 2022-04-11 18:54

import django.contrib.postgres.indexes
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loot', '0009_auto_20211017_1850'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='loot',
            index=django.contrib.postgres.indexes.GinIndex(fields=['name'], name='loot_name_gin_idx', opclasses=['gin_trgm_ops']),
        ),
    ]
