# Generated by Django 4.1.3 on 2022-11-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loot", "0012_historicalloot_aliases_loot_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalloot",
            name="former",
            field=models.BooleanField(default=False, verbose_name="Former"),
        ),
        migrations.AddField(
            model_name="loot",
            name="former",
            field=models.BooleanField(default=False, verbose_name="Former"),
        ),
    ]
