# Generated by Django 4.1.3 on 2022-11-19 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("loot", "0013_historicalloot_former_loot_former"),
    ]

    operations = [
        migrations.CreateModel(
            name="LootType",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=1000, verbose_name="Name")),
            ],
        ),
        migrations.AddField(
            model_name="historicalloot",
            name="type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="loot.loottype",
                verbose_name="Type",
            ),
        ),
        migrations.AddField(
            model_name="loot",
            name="type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="loot",
                to="loot.loottype",
                verbose_name="Type",
            ),
        ),
    ]
