# Generated by Django 4.1.3 on 2022-11-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loot", "0014_loottype_historicalloot_type_loot_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="loottype",
            name="slug",
            field=models.SlugField(default="defaultslug", editable=False, unique=True),
            preserve_default=False,
        ),
    ]
