# Generated by Django 4.1.3 on 2022-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("loot", "0015_loottype_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalloot",
            name="linked_objects",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="loot",
            name="linked_objects",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
