# Generated by Django 3.2.6 on 2021-08-29 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models
import sorl.thumbnail.fields
import utils.colors


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCharacter',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('description_md', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True, editable=False)),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.SlugField(editable=False)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default=utils.colors.get_random_color, max_length=6)),
                ('image', models.TextField(blank=True, max_length=100, null=True)),
                ('created', models.DateTimeField(blank=True, editable=False)),
                ('last_modified', models.DateTimeField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('player', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical character',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_md', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True, editable=False)),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('subtitle', models.CharField(blank=True, max_length=100)),
                ('color', models.CharField(default=utils.colors.get_random_color, max_length=6)),
                ('image', sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='character_images')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
