# Generated by Django 3.2.7 on 2021-09-14 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0003_auto_20210906_2011'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='image',
            new_name='token_image',
        ),
        migrations.RenameField(
            model_name='historicalcharacter',
            old_name='image',
            new_name='token_image',
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to=settings.AUTH_USER_MODEL),
        ),
    ]
