# Generated by Django 3.2.7 on 2021-09-14 16:44

from django.db import migrations, models
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0004_auto_20210914_1841'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='large_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='character_images'),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='large_image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
