# Generated by Django 3.2.7 on 2021-09-14 17:15

from django.db import migrations
import sorl.thumbnail.fields
import utils.random_filename


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0005_auto_20210914_1844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='large_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=utils.random_filename.get_file_path),
        ),
        migrations.AlterField(
            model_name='character',
            name='token_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=utils.random_filename.get_file_path),
        ),
    ]
