# Generated by Django 3.2.7 on 2021-09-25 17:30

import characters.models
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import sorl.thumbnail.fields
import utils.colors
import utils.random_filename


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0005_auto_20210925_1930'),
        ('characters', '0007_auto_20210923_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['name'], 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AlterModelOptions(
            name='historicalcharacter',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Character'},
        ),
        migrations.AlterField(
            model_name='character',
            name='color',
            field=models.CharField(default=utils.colors.get_random_color, max_length=7, validators=[django.core.validators.MinLengthValidator(7), characters.models.validate_color_hex], verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='character',
            name='large_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=utils.random_filename.get_file_path, verbose_name='Large Image'),
        ),
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.ForeignKey(blank=True, help_text='If no player is selected, this character is considered an NPC.', null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='character',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='character',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='character',
            name='token_image',
            field=sorl.thumbnail.fields.ImageField(blank=True, help_text='round', null=True, upload_to=utils.random_filename.get_file_path, verbose_name='Token Image'),
        ),
        migrations.AlterField(
            model_name='historicalcharacter',
            name='color',
            field=models.CharField(default=utils.colors.get_random_color, max_length=7, validators=[django.core.validators.MinLengthValidator(7), characters.models.validate_color_hex], verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='historicalcharacter',
            name='large_image',
            field=models.TextField(blank=True, max_length=100, null=True, verbose_name='Large Image'),
        ),
        migrations.AlterField(
            model_name='historicalcharacter',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If no player is selected, this character is considered an NPC.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='historicalcharacter',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='historicalcharacter',
            name='player',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='historicalcharacter',
            name='subtitle',
            field=models.CharField(blank=True, max_length=100, verbose_name='Subtitle'),
        ),
        migrations.AlterField(
            model_name='historicalcharacter',
            name='token_image',
            field=models.TextField(blank=True, help_text='round', max_length=100, null=True, verbose_name='Token Image'),
        ),
    ]
