# Generated by Django 3.2.7 on 2021-09-29 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0006_auto_20210925_2028'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('characters', '0008_auto_20210925_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='locations.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='character',
            name='player',
            field=models.ForeignKey(blank=True, help_text='If no player is selected, this character is considered an NPC.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
        migrations.AlterField(
            model_name='historicalcharacter',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='locations.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='historicalcharacter',
            name='player',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='If no player is selected, this character is considered an NPC.', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Player'),
        ),
    ]
