# Generated by Django 3.2.7 on 2021-10-03 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0009_auto_20210929_2151'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nickname'),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nickname'),
        ),
    ]
