# Generated by Django 3.2.7 on 2021-10-03 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0001_initial'),
        ('characters', '0010_auto_20211003_1554'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='factions.faction', verbose_name='Faction'),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='faction',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='factions.faction', verbose_name='Faction'),
        ),
    ]
