# Generated by Django 3.2.7 on 2021-10-07 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('factions', '0001_initial'),
        ('characters', '0011_auto_20211003_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='faction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='characters', to='factions.faction', verbose_name='Faction'),
        ),
    ]
