# Generated by Django 3.2.8 on 2021-11-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0012_alter_character_faction'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='character',
            options={'ordering': ['archived', 'name'], 'verbose_name': 'Character', 'verbose_name_plural': 'Characters'},
        ),
        migrations.AddField(
            model_name='character',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='archived',
            field=models.BooleanField(default=False, verbose_name='Archived'),
        ),
    ]
