# Generated by Django 4.0.5 on 2022-06-19 11:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0014_character_character_name_gin_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalcharacter',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Character', 'verbose_name_plural': 'historical Characters'},
        ),
        migrations.AddField(
            model_name='character',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Nickname'), blank=True, null=True, size=None, verbose_name='Aliases'),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='aliases',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100, verbose_name='Nickname'), blank=True, null=True, size=None, verbose_name='Aliases'),
        ),
        migrations.AlterField(
            model_name='historicalcharacter',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
