# Generated by Django 4.0.5 on 2022-06-19 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('characters', '0015_alter_historicalcharacter_options_character_aliases_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='nickname',
        ),
        migrations.RemoveField(
            model_name='historicalcharacter',
            name='nickname',
        ),
    ]
