# Generated by Django 4.1.3 on 2022-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0016_remove_character_nickname_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="character",
            name="linked_objects",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="historicalcharacter",
            name="linked_objects",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
