# Generated by Django 5.0.8 on 2024-08-07 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("characters", "0017_character_linked_objects_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="character",
            name="subtitle",
        ),
        migrations.RemoveField(
            model_name="historicalcharacter",
            name="subtitle",
        ),
    ]
