# Generated by Django 4.0.5 on 2022-07-05 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='draft',
            options={'get_latest_by': 'created'},
        ),
    ]
