# Generated by Django 3.2.6 on 2021-08-22 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20210822_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='faction',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='loot',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
