# Generated by Django 4.0.5 on 2022-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_note_name_gin_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalnote',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Note', 'verbose_name_plural': 'historical Notes'},
        ),
        migrations.AlterField(
            model_name='historicalnote',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
