# Generated by Django 3.2.6 on 2021-08-22 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_historicalcampaign_historicalcharacter_historicalfaction_historicallocation_historicalloot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='faction',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(editable=False),
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('campaign', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='faction',
            unique_together={('campaign', 'slug')},
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together={('campaign', 'slug')},
        ),
    ]
