# Generated by Django 4.1.3 on 2022-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_historicalnote_aliases_note_aliases"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnote",
            name="linked_objects",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="note",
            name="linked_objects",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
