# Generated by Django 3.2.6 on 2021-08-22 16:10

from django.db import migrations, models
import notes.utils.colors


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20210822_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='color',
            field=models.CharField(default=notes.utils.colors.get_random_color, max_length=6),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='color',
            field=models.CharField(default=notes.utils.colors.get_random_color, max_length=6),
        ),
    ]
