# Generated by Django 3.2.6 on 2021-08-22 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0008_auto_20210822_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='character_images'),
        ),
        migrations.AddField(
            model_name='historicalcharacter',
            name='image',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
    ]
