# Generated by Django 3.2.6 on 2021-08-22 17:09

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0009_auto_20210822_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='character_images'),
        ),
    ]
