# Generated by Django 3.2.6 on 2021-08-23 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0011_auto_20210822_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingameday',
            name='sessions',
            field=models.ManyToManyField(related_name='ingame_days', to='notes.Session'),
        ),
        migrations.AlterUniqueTogether(
            name='ingameday',
            unique_together={('campaign', 'day')},
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together={('campaign', 'day')},
        ),
        migrations.RemoveField(
            model_name='session',
            name='ingame_days',
        ),
    ]
