# Generated by Django 3.2.6 on 2021-08-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0013_auto_20210823_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='dm',
        ),
        migrations.RemoveField(
            model_name='character',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='historicalcharacter',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='historicalfaction',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='historicalingameday',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='historicallocation',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='historicalloot',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='historicalsession',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='loot',
            name='campaign',
        ),
        migrations.AlterUniqueTogether(
            name='faction',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='ingameday',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='location',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='session',
            unique_together=set(),
        ),
        migrations.DeleteModel(
            name='HistoricalCampaign',
        ),
        migrations.RemoveField(
            model_name='faction',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='ingameday',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='location',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='session',
            name='campaign',
        ),
        migrations.DeleteModel(
            name='Campaign',
        ),
    ]
