# Generated by Django 3.2.6 on 2021-08-29 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0015_auto_20210828_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalloot',
            name='owner',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='notes.character'),
        ),
        migrations.AlterField(
            model_name='loot',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='notes.character'),
        ),
    ]
