declare module "luminous-lightbox" {
    /** Declaration file generated by dts-gen */

    export class Luminous {
        constructor(trigger: any, ...args: any[]);

        close(e: any): void;

        destroy(): void;

        open(e: any): void;

    }

    export class LuminousGallery {
        constructor(triggers: NodeListOf<Element>, ...args: any[]);

        destroy(): any;

        nextTrigger(trigger: any): any;

        onChange(_ref: any): void;

        previousTrigger(trigger: any): any;

    }

}
