# Generated by Django 3.2.7 on 2021-09-25 17:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0002_auto_20210923_2101'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalsession',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Session'},
        ),
        migrations.AlterModelOptions(
            name='session',
            options={'ordering': ['-date'], 'verbose_name': 'Session', 'verbose_name_plural': 'Sessions'},
        ),
        migrations.RemoveField(
            model_name='historicalsession',
            name='day',
        ),
        migrations.RemoveField(
            model_name='session',
            name='day',
        ),
        migrations.AddField(
            model_name='historicalsession',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='historicalingameday',
            name='day',
            field=models.PositiveIntegerField(verbose_name='Day'),
        ),
        migrations.AlterField(
            model_name='ingameday',
            name='day',
            field=models.PositiveIntegerField(verbose_name='Day'),
        ),
    ]
