# Generated by Django 3.2.7 on 2021-09-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0003_auto_20210925_1930'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalingameday',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Day'},
        ),
        migrations.AlterModelOptions(
            name='ingameday',
            options={'ordering': ['-day'], 'verbose_name': 'Day', 'verbose_name_plural': 'Days'},
        ),
        migrations.AlterField(
            model_name='ingameday',
            name='sessions',
            field=models.ManyToManyField(related_name='ingame_days', to='days.Session', verbose_name='Session'),
        ),
    ]
