# Generated by Django 4.0.5 on 2022-06-19 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0004_auto_20210925_1932'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='historicalingameday',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Day', 'verbose_name_plural': 'historical Days'},
        ),
        migrations.AlterModelOptions(
            name='historicalsession',
            options={'get_latest_by': ('history_date', 'history_id'), 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Session', 'verbose_name_plural': 'historical Sessions'},
        ),
        migrations.AlterField(
            model_name='historicalingameday',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='historicalsession',
            name='history_date',
            field=models.DateTimeField(db_index=True),
        ),
    ]
