# Generated by Django 4.0.5 on 2022-06-19 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('days', '0005_alter_historicalingameday_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalsession',
            name='date',
            field=models.DateField(db_index=True, default=datetime.date.today, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='session',
            name='date',
            field=models.DateField(default=datetime.date.today, unique=True, verbose_name='Date'),
        ),
    ]
