# Generated by Django 4.1.3 on 2022-11-25 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("days", "0006_alter_historicalsession_date_alter_session_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalingameday",
            name="linked_objects",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
        migrations.AddField(
            model_name="ingameday",
            name="linked_objects",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
