# Generated by Django 5.1.8 on 2025-04-22 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("days", "0008_alter_session_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalingameday",
            name="day",
            field=models.PositiveIntegerField(db_index=True, verbose_name="Day"),
        ),
        migrations.AlterField(
            model_name="ingameday",
            name="day",
            field=models.PositiveIntegerField(unique=True, verbose_name="Day"),
        ),
    ]
