# Generated by Django 4.0.3 on 2022-04-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0004_alter_campaign_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='language',
            field=models.CharField(default='english', max_length=100, verbose_name='Language'),
            preserve_default=False,
        ),
    ]
