# Generated by Django 4.1.3 on 2022-11-16 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0005_campaign_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="created",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="language",
            field=models.CharField(
                choices=[
                    ("simple", "Other"),
                    ("arabic", "Arabic"),
                    ("danish", "Danish"),
                    ("dutch", "Dutch"),
                    ("english", "English"),
                    ("finnish", "Finnish"),
                    ("french", "French"),
                    ("german", "German"),
                    ("greek", "Greek"),
                    ("hungarian", "Hungarian"),
                    ("indonesian", "Indonesian"),
                    ("irish", "Irish"),
                    ("italian", "Italian"),
                    ("lithuanian", "Lithuanian"),
                    ("nepali", "Nepali"),
                    ("norwegian", "Norwegian"),
                    ("portuguese", "Portuguese"),
                    ("romanian", "Romanian"),
                    ("russian", "Russian"),
                    ("spanish", "Spanish"),
                    ("swedish", "Swedish"),
                    ("tamil", "Tamil"),
                    ("turkish", "Turkish"),
                ],
                max_length=100,
                verbose_name="Language",
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="modified",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
