# Generated by Django 4.2.1 on 2023-05-28 13:54

from django.db import migrations, models
import utils.random_filename


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0006_alter_campaign_created_alter_campaign_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="document",
            field=models.FileField(
                blank=True,
                editable=False,
                null=True,
                upload_to=utils.random_filename.get_file_path,
                verbose_name="Document",
            ),
        ),
    ]
