# Generated by Django 4.2.5 on 2023-09-18 14:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaigns", "0007_campaign_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="language",
            field=models.CharField(
                choices=[
                    ("simple", "Other"),
                    ("arabic", "Arabic"),
                    ("danish", "Danish"),
                    ("dutch", "Dutch"),
                    ("english", "English"),
                    ("finnish", "Finnish"),
                    ("french", "French"),
                    ("german", "German"),
                    ("greek", "Greek"),
                    ("hungarian", "Hungarian"),
                    ("indonesian", "Indonesian"),
                    ("irish", "Irish"),
                    ("italian", "Italian"),
                    ("lithuanian", "Lithuanian"),
                    ("nepali", "Nepali"),
                    ("norwegian", "Norwegian"),
                    ("portuguese", "Portuguese"),
                    ("romanian", "Romanian"),
                    ("russian", "Russian"),
                    ("spanish", "Spanish"),
                    ("swedish", "Swedish"),
                    ("tamil", "Tamil"),
                    ("turkish", "Turkish"),
                ],
                help_text="This is needed for the full text search to work optimally.",
                max_length=100,
                verbose_name="Language",
            ),
        ),
    ]
