# Generated by Django 3.2.7 on 2021-09-06 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description_md', models.TextField(blank=True)),
                ('description_html', models.TextField(blank=True, editable=False)),
                ('name', models.CharField(max_length=1000)),
                ('slug', models.SlugField(editable=False, unique=True)),
                ('part_of', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='locations.location')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
