# Generated by Django 3.2.7 on 2021-09-25 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0004_auto_20210923_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallocation',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=1000, verbose_name='Name'),
        ),
    ]
